[phases.setup]
nixPkgs = ["python3", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt", "npm ci"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput"]

[phases.start]
cmds = ["python3 manage.py bootstrap_runtime && uvicorn config.asgi:application --host 0.0.0.0 --port $PORT --workers 2 --loop uvloop --http httptools --timeout-keep-alive 120"]
