[phases.setup]
nixPkgs = ["python3", "nodejs_18", "npm-9_x"]

[phases.install]
cmds = ["python3 -m pip install -r requirements.txt", "npm ci"]

[phases.build]
cmds = ["python3 manage.py collectstatic --noinput"]

[phases.start]
cmds = ["python3 manage.py migrate --noinput && python3 manage.py ensure_ssambti && python3 manage.py ensure_studentmbti && python3 manage.py ensure_notebooklm && gunicorn config.wsgi --log-file - --timeout 120"]
